services:
  - type: web
    name: eazyvenue-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port 10000
    runtime: python
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        value: sqlite:///./venues.db
    staticPublishPath: static

